//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventRegist = new HashSet<EventRegist>();
            this.EventSign = new HashSet<EventSign>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string EmailContent { get; set; }
        public string MasterEmail { get; set; }
        public Nullable<System.DateTime> EventStart { get; set; }
        public Nullable<System.DateTime> EventEnd { get; set; }
        public Nullable<System.DateTime> SignStart { get; set; }
        public Nullable<System.DateTime> SignEnd { get; set; }
        public bool IsOpen { get; set; }
        public bool IsNumLimited { get; set; }
        public Nullable<int> LimitedNum { get; set; }
        public Nullable<byte> SendNote { get; set; }
        public string CfmEmailContent { get; set; }
        public string Agreement { get; set; }
        public bool IsPwLimited { get; set; }
        public string LimitedPw { get; set; }
        public int UserId { get; set; }
        public string TitleImgPath { get; set; }
        public Nullable<int> ViewNum { get; set; }
        public bool IsChangeViewNum { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Address { get; set; }
        public Nullable<int> QRcodeMode { get; set; }
        public string QRCodePassword { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRegist> EventRegist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventSign> EventSign { get; set; }
    }
}
