//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventSign()
        {
            this.EventDropList = new HashSet<EventDropList>();
        }
    
        public int ID { get; set; }
        public int EventId { get; set; }
        public int TypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> MinLen { get; set; }
        public Nullable<int> MaxLen { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<byte> UseType { get; set; }
    
        public virtual ColumnType ColumnType { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDropList> EventDropList { get; set; }
    }
}
